FROM alpine:3.24

RUN apk upgrade --no-cache \
  && apk add --no-cache nodejs-current=26.5.1-r0 npm

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server with hot reloading
CMD ["npm", "run", "start:dev"]
