packages:
  - "."

autoInstallPeers: false

overrides:
  '@babel/core@^7': 7.29.6
  '@eslint/plugin-kit@^0.3': 0.3.4
  '@smithy/config-resolver@^4': 4.4.0
  '@xhmikosr/decompress@^10': 10.2.1
  'ajv@^6': 6.14.0
  'ajv@^8': 8.20.0
  axios: 1.18.1
  'body-parser@^2': 2.3.0
  'brace-expansion@^1': 1.1.16
  'brace-expansion@^2': 2.1.2
  defu: 6.1.7
  'diff@^4': 4.0.4
  effect: 3.22.0
  'fast-uri@^3': 3.1.4
  'fast-xml-parser@^5': 5.10.1
  'file-type@>=13.0.0 <21.3.2': 21.3.2
  flatted: 3.4.2
  follow-redirects: 1.16.0
  form-data: 4.0.6
  joi: 18.2.3
  'js-yaml@^4': 4.3.0
  jws: 4.0.1
  lodash: 4.18.1
  'minimatch@^3': 3.1.5
  'minimatch@^5': 5.1.8
  'minimatch@^9': 9.0.9
  multer: 2.2.0
  path-to-regexp: 8.4.2
  'picomatch@^2': 2.3.2
  'picomatch@^4': 4.0.5
  'piscina@^4': 4.9.3
  qs: 6.15.3
  tmp: 0.2.7
  validator: 13.15.35
  yaml: 2.9.0
  yauzl: 3.2.1

allowBuilds:
  '@prisma/client@6.19.3': true
  '@prisma/engines@6.19.3': true
  '@scarf/scarf@1.4.0': false
  '@swc/core@1.12.14': true
  'esbuild@0.25.10': true
  'msgpackr-extract@3.0.4': true
  'prisma@6.19.3': true
